# Generated by Django 3.2.4 on 2021-06-06 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0004_auto_20210604_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unsuccesful_Mpesa_payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MerchantRequestID', models.CharField(max_length=50)),
                ('CheckoutRequestID', models.CharField(max_length=50)),
                ('ResultCode', models.IntegerField()),
                ('ResultDesc', models.TextField()),
                ('Paid_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.item')),
                ('Paying_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
            ],
            options={
                'verbose_name': 'unsuccesful Mpesa transaction',
                'verbose_name_plural': 'unsuccesful Mpesa transactions',
            },
        ),
        migrations.CreateModel(
            name='Succesful_Mpesa_payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MerchantRequestID', models.CharField(max_length=50)),
                ('CheckoutRequestID', models.CharField(max_length=50)),
                ('ResultCode', models.IntegerField()),
                ('ResultDesc', models.TextField()),
                ('Amount', models.DecimalField(decimal_places=3, max_digits=13)),
                ('MpesaReceiptNumber', models.CharField(max_length=50)),
                ('Balance', models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True)),
                ('TransactionDate', models.DateTimeField()),
                ('PhoneNumber', models.CharField(max_length=13)),
                ('payment_for', models.CharField(max_length=50)),
                ('Paid_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.item')),
                ('Paying_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
            ],
            options={
                'verbose_name': 'Succesful Mpesa Payment',
                'verbose_name_plural': 'Succesful Mpesa Payments',
            },
        ),
        migrations.CreateModel(
            name='Mpesa_api_Responses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MerchantRequestID', models.CharField(max_length=50)),
                ('CheckoutRequestID', models.CharField(max_length=50)),
                ('ResponseCode', models.IntegerField()),
                ('ResponseDescription', models.TextField()),
                ('CustomerMessage', models.TextField()),
                ('the_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
            ],
            options={
                'verbose_name': 'Mpesa Response',
                'verbose_name_plural': 'Mpesa Responses',
            },
        ),
    ]
