# Generated by Django 3.2.4 on 2021-06-06 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mpesa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='succesful_mpesa_payments',
            name='Paid_item',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='succesful_mpesa_payments',
            name='Paying_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
