# Generated by Django 3.2.4 on 2021-06-07 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0004_alter_succesful_mpesa_payments_paid_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='succesful_mpesa_payments',
            name='Paid_item',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='unsuccesful_mpesa_payments',
            name='Paid_item',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
