# Generated by Django 3.2.4 on 2021-06-09 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0005_auto_20210607_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesa_api_responses',
            name='paid_item',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
