# Generated by Django 3.2.4 on 2021-06-09 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0006_mpesa_api_responses_paid_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpesa_api_responses',
            name='the_user',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
