# Generated by Django 3.2.4 on 2021-07-02 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0008_auto_20210702_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='succesful_mpesa_payments',
            name='Amount',
            field=models.DecimalField(decimal_places=3, max_digits=213),
        ),
        migrations.AlterField(
            model_name='succesful_mpesa_payments',
            name='Balance',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=213, null=True),
        ),
        migrations.AlterField(
            model_name='succesful_mpesa_payments',
            name='PhoneNumber',
            field=models.CharField(max_length=20),
        ),
    ]
