# Generated by Django 3.2.4 on 2021-06-09 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_interested_items_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interested_items',
            name='date_int',
            field=models.DateTimeField(),
        ),
    ]
