# Generated by Django 3.2.4 on 2021-06-09 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_interested_items_date_int'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interested_items',
            name='date_int',
        ),
    ]
