# Generated by Django 3.2.4 on 2021-06-09 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20210609_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='interested_items',
            name='date_paid',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='date_paid',
            field=models.DateTimeField(null=True),
        ),
    ]
