# Generated by Django 3.2.4 on 2021-06-18 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20210609_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='activeauction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('amount_bid', models.FloatField(max_length=50)),
            ],
        ),
    ]
