# Generated by Django 3.2.4 on 2021-07-04 01:17

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_category_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='date_scheduled',
            field=models.DateField(default=user.models.item.return_date_time),
        ),
    ]
